trigger:
  branches:
    include:
      - master
  paths:
    include:
      - infra/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'aks-microservices-connection'
    namespace: 'microservices'
    manifests: |
      infra/k8s/namespace.yml
      infra/k8s/redis.yml
      infra/k8s/zipkin.yml
      infra/k8s/ingress.yml
    
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks-microservices-connection'
    command: 'get'
    arguments: 'pods,services,ingress -n microservices'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Obtener credenciales del cluster
      az aks get-credentials --resource-group microservices-rg --name microservices-aks --overwrite-existing
      
      # Ejecutar el script de inicio
      chmod +x $(System.DefaultWorkingDirectory)/infra/start-services.sh
      $(System.DefaultWorkingDirectory)/infra/start-services.sh 