name: Infrastructure Pipeline

on:
  push:
    paths:
      - 'infra/**'
    branches:
      - main
  pull_request:
    paths:
      - 'infra/**'

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=./kubeconfig.yaml

      - name: Create namespace if not exists
        run: kubectl apply -f infra/k8s/namespace.yml

      - name: Deploy Core Infrastructure
        run: |
          kubectl apply -f infra/k8s/redis.yml
          kubectl apply -f infra/k8s/zipkin.yml
          kubectl apply -f infra/k8s/ingress.yml

      - name: Verify Infrastructure
        run: |
          kubectl get pods -n microservices
          kubectl get services -n microservices
          kubectl get ingress -n microservices
