trigger: none # Manual trigger only

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Obtener credenciales del cluster
      az aks get-credentials --resource-group microservices-rg --name microservices-aks --overwrite-existing
      
      # Ejecutar el script de parada
      chmod +x $(System.DefaultWorkingDirectory)/infra/stop-services.sh
      $(System.DefaultWorkingDirectory)/infra/stop-services.sh

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks-microservices-connection'
    command: 'get'
    arguments: 'pods -n microservices'

- task: Bash@3
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/infra/stop-services.sh'
    failOnStderr: false 