apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microservices
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: microservicesacr2025.azurecr.io/frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: AUTH_API_ADDRESS
          value: "http://auth-api:8080"
        - name: TODOS_API_ADDRESS
          value: "http://todos-api:8080"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m" 
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: microservices
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP 