trigger:
  branches:
    include:
      - master
  paths:
    include:
      - users-api/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: 'users-api'
  containerRegistry: 'microservicesacr2025.azurecr.io'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'acr-microservices-connection'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: 'users-api/Dockerfile'
        tags: |
          $(tag)
          latest

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'aks-microservices-connection'
        command: 'get'
        arguments: 'pods -n microservices'
        
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceEndpoint: 'aks-microservices-connection'
        namespace: 'microservices'
        manifests: 'users-api/k8s/deployment.yml'
        containers: '$(containerRegistry)/$(imageRepository):$(tag)'
        rolloutStatusTimeout: '300'

    - task: Kubernetes@1
      condition: succeededOrFailed()
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'aks-microservices-connection'
        command: 'logs'
        arguments: '-l app=users-api -n microservices --tail=100'