apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
  namespace: microservices
spec:
  selector:
    matchLabels:
      app: todos-api
  replicas: 1
  template:
    metadata:
      labels:
        app: todos-api
    spec:
      containers:
      - name: todos-api
        image: elgris/microservice-app-example-todos-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: ZIPKIN_URL
          value: "http://zipkin:9411/api/v2/spans"
        - name: AUTH_API_ADDRESS
          value: "http://auth-api:8080"
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m" 