apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
  namespace: microservices
spec:
  selector:
    matchLabels:
      app: todos-api
  replicas: 1
  template:
    metadata:
      labels:
        app: todos-api
    spec:
      containers:
      - name: todos-api
        image: microservicesacr2025.azurecr.io/todos-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: AUTH_API_ADDRESS
          value: "http://auth-api:8080"
        - name: ZIPKIN_URL
          value: "http://zipkin:9411/api/v2/spans"
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m" 
---
apiVersion: v1
kind: Service
metadata:
  name: todos-api
  namespace: microservices
  labels:
    app: todos-api
spec:
  selector:
    app: todos-api
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 