apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: microservices
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /auth/(.*)
        pathType: Prefix
        backend:
          service:
            name: auth-api
            port:
              number: 8080
      - path: /todos/(.*)
        pathType: Prefix
        backend:
          service:
            name: todos-api
            port:
              number: 8080
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80 