trigger:
  branches:
    include:
      - master
  paths:
    include:
      - log-message-processor/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: 'log-message-processor'
  containerRegistry: 'microservicesacr2025.azurecr.io'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push
  jobs:
    - job: Build
      steps:
        - task: Docker@2
          displayName: Build and Push Image
          inputs:
            containerRegistry: 'acr-microservices-connection'
            repository: '$(imageRepository)'
            command: 'buildAndPush'
            Dockerfile: 'log-message-processor/Dockerfile'
            tags: |
              $(tag)
              latest

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  condition: succeeded()
  jobs:
    - job: Deploy
      steps:
        - task: Kubernetes@1
          displayName: Check Cluster Status
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: 'aks-microservices-connection'
            command: 'get'
            arguments: 'nodes'

        - task: Kubernetes@1
          displayName: Deploy Application
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: 'aks-microservices-connection'
            command: 'apply'
            arguments: '-f log-message-processor/k8s/deployment.yml'

        - task: Kubernetes@1
          displayName: Update Image
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: 'aks-microservices-connection'
            command: 'set'
            arguments: 'image deployment/log-message-processor log-message-processor=$(containerRegistry)/$(imageRepository):$(tag) -n microservices'

        - task: Kubernetes@1
          displayName: Get Pod Status
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: 'aks-microservices-connection'
            command: 'get'
            arguments: 'pods -n microservices -l app=log-message-processor -o wide'

        - task: Kubernetes@1
          displayName: Get Pod Logs
          condition: succeededOrFailed()
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: 'aks-microservices-connection'
            command: 'logs'
            arguments: '-l app=log-message-processor -n microservices --tail=100'
